language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: oIm+fxVPrFnNgNUJAauv4G39x1exvu0yt0nR6RRlAmKUGacVUSnkRArD0OpMhxTtYXnpZ4C6ZODKRUtVlY1MV0blGXx4iUiIKT56bvsL34UbXnvZ1dxV2KR9Hjw7f142ZQHx6vSoVQQLUJUqZMb3mJ65WcECqhqI4bCH4eQi3+0IUMzMbPGY3nTsVxDLXxKmCaS5GMS/Kfg4BuwCm5MOSLFGUG8Z4ED1YBAccWy6+0ijARIKhp/LJYBcnmOSVk4DqWh6HnI3Grx0yDwAS6uOUgOu38uPqzuaGND2qWeSFoCUCeNgWCGx9Bw7gx/vzAoH0HvSL32SNClCpSuwVKMKEBem49TeHGXt7pEIUk74tym7JTOuftw0ECU+wLxJ1DgH2WbF2skIoPSE7eJYi6yUq3ilw5sw/0PF/x7HeB3yfnXvk509TfDQQIGWhRtCpUyFbDZ8LL4oomC6jq6OCufSdUIa8L4up4IMGY410x92U6ZvfaLcGF8tg8fsDHoWeG11TTzdYXRs48tBj3NlHGmZu2XY3MKlqoyN5HDxgK0zNQQclDzO1XClCI0hjbTWJ1So3Pklbwf3e9eV7TFPF4zFIU70eV6XLOzBOyHN0DAvF5yBIH6dV3MBn9PKnN1StvnpmcIvbrEk7aj2HlwyQ7aj75te/O9OTthrL8fHkxyddJY=
  app: shri-2016-task6
  on:
    repo: reindeers/shri-2016-task6
