language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: KaRptdrtxitD5yyWiSzUp3BX1y8xGtCwWJFNOQhULOV45zYW8x8rHD3SzJlWtAF31MKBft1HGr5E5t9AE2u3xImrsMpsS9GRdU71LhgIWLlV7zUI3Bf4oNc36bNfeli+OeHykwwGJBVgJsAeXuAZYMN0S1kQvYb3lVUFYNvRL6thXa32F/JIg4+mD4d8MxljSVJPQPZnvf4EQn4+8ckYpWpoXxn0dsNPphd/N2/f/2pSi+uSIL7Ct7OFqkzwETNWKMGrtJJWoqQX6mXfLDRNilUENDtp2fHlD01+MfGY7XGKsDLWHxzI8fOxVdZ67KRgPMYxf4SDzYPlr8yOrDmHrgo/iICVeu8TzkJ688pkD3mOvc80s+PNExGafD5/gKlNl3ShvbrGnRCgjnI4UmontmipR5LicpGvFZNhPpznfm5s+eTX9jR054/zym3bduR+kl6sb7cIeKvRSjnusw63M6fURwYXAwOK6WDGUNJB5MrrhKBTl+GWPLyQt+uXxkW3hrpvLGhQt/iDyhxl/Hdv1KQ1gwDm5PTfJuYcynSMIOuNiGQ7qYyUXXvxvjI/Ao4eWlzu8+VFEt8WoVqQITjpu6RMsG0BYGnLSkldQB0mXD9G6cTEb8OftUrnuk4KhVN4b/3cjgN8lBcRV0VAYMgRQPr7X/5tkdiytLyOENbme5w=
